/*
 * Copyright (c) 2020, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <stdbool.h>
#include <ti/drivers/PIN.h>
#include <ti/drivers/ITM.h>
#include <ti/drivers/pin/PINCC26XX.h>
#include <ti/drivers/itm/ITMCC26XX.h>

/* This enables the device specific hwAttrs to be case as the generic ones
 * The hwAttrs will be generated by syscfg
 */
extern void *itmHwAttrs;

static PIN_Handle          swoPinHandle; /* SWO PIN handle */
static PIN_State           swoPinState;  /* SWO PIN state structure */
/*
 *  ======== ITM_applyPinMux ========
 */
bool ITM_applyPinMux(void)
{
    ITMCC26XX_HWAttrs *hwAttrs = (ITMCC26XX_HWAttrs *)itmHwAttrs;
    PIN_Config swoPinTable[2];
    swoPinTable[0] = hwAttrs->swoPin | PIN_INPUT_EN | PIN_GPIO_OUTPUT_EN | PIN_GPIO_HIGH;
    swoPinTable[1] = PIN_TERMINATE;

    /* PIN_open is a heavy function. It takes around ~100us and must be
     * called in a task context because it pends a semaphore forever.
     *
     * Users who wish to avoid this should consider replacing the pin calls
     * below with driverlib API in this comment block.
     *
     * WARNING: This offers no pin protection against other clients.
     * Only use this if you are sure no other code will touch this pin.
     * Replace IOID_X with the proper IOID.
     *
     * IOCPortConfigureSet(IOID_X, IOC_PORT_MCU_SWV, IOC_STD_OUTPUT);
     */
    swoPinHandle = PIN_open(&swoPinState, swoPinTable);

    if (NULL == swoPinHandle)
    {
        return (bool)false;
    }

    PINCC26XX_setMux(swoPinHandle, hwAttrs->swoPin, IOC_PORT_MCU_SWV);

    return (bool)true;
}

/*
 *  ======== ITM_clearPinMux ========
 */
void ITM_clearPinMux(void)
{
    PIN_close(swoPinHandle);
}


/*
 *  ======== ITMCC26XX_Flush ========
 */
void ITMCC26XX_flush()
{
    ITMCC26XX_HWAttrs *hwAttrs = (ITMCC26XX_HWAttrs *)itmHwAttrs;
    /* Release the SWO pin from the ITM */
    PINCC26XX_setMux(swoPinHandle, hwAttrs->swoPin, IOC_PORT_GPIO);
}

/*
 *  ======== ITMCC26XX_restore ========
 */
void ITMCC26XX_restore(void)
{
    ITMCC26XX_HWAttrs *hwAttrs = (ITMCC26XX_HWAttrs *)itmHwAttrs;
    /* Return SWO pin to the ITM hardware*/
    PINCC26XX_setMux(swoPinHandle, hwAttrs->swoPin, IOC_PORT_MCU_SWV);
}
